version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: src.configuration.CustomerFileHandler
        level: INFO
        formatter: simple
        filename: logs/info.log
        # 100MB
        maxBytes: 104857600
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: src.configuration.CustomerFileHandler
        level: ERROR
        formatter: simple
        filename: logs/errors.log
        # 100MB
        maxBytes: 104857600
        backupCount: 20
        encoding: utf8

loggers:
    my_module:
        level: ERROR
        handlers: [console]
        propagate: no

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
